include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**/*.mapper.g.dart
    - lib/**/*.config.dart
    - lib/**/*.g.dart
    - lib/**/*.gr.dart
    - lib/**/*.gen.dart
  strong-mode:
    implicit-casts: false
  errors:
    camel_case_types: error

linter:
  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    always_put_required_named_parameters_first: false

    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # ------ Enable individual rules ------ #
    #                 ---                   #
    # These rules here are good but too     #
    # opinionated to enable them by default #
    # ------------------------------------- #

    # Make constructors the first thing in every class
    sort_constructors_first: false

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true

    # Good packages document everything
    public_member_api_docs: true

    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Back to the 80s
    lines_longer_than_80_chars: false

    # allow trycatch withtout catch clause
    avoid_catches_without_on_clauses: false

    library_prefixes: false
    parameter_assignments: false
    sort_pub_dependencies: false
